global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'stream-analytics-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['192.168.0.106:8082'] ## Replace your system(local) IP address
        labels:
          application: 'Stream Analytics Application'